name: Forest Residue Analysis
on: [push]

jobs:
  analyze-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Reduced from 15
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            r-base-dev \
            libmysqlclient-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libfontconfig1-dev  # For ggplot2 text rendering

      - name: Configure R environment
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Binary packages for Ubuntu 22.04

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages-${{ hashFiles('requirements.R') }}
          restore-keys: ${{ runner.os }}-r-packages-

      - name: Install essential packages first
        run: |
          Rscript -e "install.packages(c('remotes', 'pak'), repos = 'https://cran.rstudio.com')"
          
      - name: Install project packages
        run: |
          Rscript -e "pak::pkg_install(deps = FALSE, ask = FALSE, upgrade = FALSE)"
          Rscript requirements.R

      - name: Run analysis pipeline
        run: |
          Rscript scripts/processing/clean_transform.R
          Rscript scripts/analysis/pyrolysis_quality.R

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-outputs
          path: outputs/