name: Forest Residue Analysis Pipeline
on: [push]

jobs:
  analyze-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Fails if job exceeds this time

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            r-base-dev \
            libmysqlclient-dev \
            libssl-dev \
            libcurl4-openssl-dev

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use RStudio Package Manager for faster installs

      - name: Install R packages
        run: Rscript requirements.R

      - name: Run data processing
        run: Rscript scripts/processing/clean_transform.R

      - name: Generate visualizations
        run: Rscript scripts/analysis/pyrolysis_quality.R

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: |
            outputs/visualizations/*.png
            outputs/results/*.csv