name: Process Data
on: [push]

jobs:
  process-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent infinite hangs
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base-dev libmysqlclient-dev libssl-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use RStudio Package Manager for binaries

      - name: Install R packages
        run: |
          Rscript requirements.R
        shell: bash
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true  # Suppress warnings as errors

      # ... rest of your steps ...