name: Process Data
on: [push]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Valid version

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Latest stable version for R setup

      - name: Install dependencies
        run: Rscript requirements.R

      - name: Validate data
        run: Rscript scripts/processing/validate_data.R

      - name: Process and analyze
        run: Rscript scripts/analysis/pyrolysis_quality.R

      - name: Upload visualizations
        uses: actions/upload-artifact@v4  # Valid version
        with:
          name: plots
          path: outputs/visualizations/*.png