name: Process Data
on: [push]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v4

      - name: Install dependencies
        run: Rscript requirements.R

      - name: Validate data
        run: Rscript scripts/processing/validate_data.R

      - name: Process data
        run: Rscript scripts/processing/clean_transform.R

      - name: Run analysis
        run: Rscript scripts/analysis/pyrolysis_quality.R

      - name: Upload visualizations
        uses: actions/upload-artifact@v3
        with:
          name: plots
          path: outputs/visualizations/*.png